name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 1v8
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.12.0
        with:
          mongodb-version: 6.0

      - name: Install Dependencies
        run: npm i
      - name: Test Production Build
        run: npm run build
      - name: Test
        run: npm run test
